// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/messages.proto

package quasar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_PULL_FILTER_REQUEST  Message_MessageType = 0
	Message_PULL_FILTER_RESPONSE Message_MessageType = 1
	Message_PUSH_FILTER_REQUEST  Message_MessageType = 2
	Message_PUSH_FILTER_RESPONE  Message_MessageType = 3
)

var Message_MessageType_name = map[int32]string{
	0: "PULL_FILTER_REQUEST",
	1: "PULL_FILTER_RESPONSE",
	2: "PUSH_FILTER_REQUEST",
	3: "PUSH_FILTER_RESPONE",
}
var Message_MessageType_value = map[string]int32{
	"PULL_FILTER_REQUEST":  0,
	"PULL_FILTER_RESPONSE": 1,
	"PUSH_FILTER_REQUEST":  2,
	"PUSH_FILTER_RESPONE":  3,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5a31b8d3937ded8, []int{4, 0}
}

type PullFiltersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFiltersRequest) Reset()         { *m = PullFiltersRequest{} }
func (m *PullFiltersRequest) String() string { return proto.CompactTextString(m) }
func (*PullFiltersRequest) ProtoMessage()    {}
func (*PullFiltersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5a31b8d3937ded8, []int{0}
}
func (m *PullFiltersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFiltersRequest.Unmarshal(m, b)
}
func (m *PullFiltersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFiltersRequest.Marshal(b, m, deterministic)
}
func (dst *PullFiltersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFiltersRequest.Merge(dst, src)
}
func (m *PullFiltersRequest) XXX_Size() int {
	return xxx_messageInfo_PullFiltersRequest.Size(m)
}
func (m *PullFiltersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFiltersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullFiltersRequest proto.InternalMessageInfo

type PullFiltersResponse struct {
	AttenuateBloomFilter []byte   `protobuf:"bytes,1,opt,name=AttenuateBloomFilter,proto3" json:"AttenuateBloomFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFiltersResponse) Reset()         { *m = PullFiltersResponse{} }
func (m *PullFiltersResponse) String() string { return proto.CompactTextString(m) }
func (*PullFiltersResponse) ProtoMessage()    {}
func (*PullFiltersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5a31b8d3937ded8, []int{1}
}
func (m *PullFiltersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFiltersResponse.Unmarshal(m, b)
}
func (m *PullFiltersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFiltersResponse.Marshal(b, m, deterministic)
}
func (dst *PullFiltersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFiltersResponse.Merge(dst, src)
}
func (m *PullFiltersResponse) XXX_Size() int {
	return xxx_messageInfo_PullFiltersResponse.Size(m)
}
func (m *PullFiltersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFiltersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullFiltersResponse proto.InternalMessageInfo

func (m *PullFiltersResponse) GetAttenuateBloomFilter() []byte {
	if m != nil {
		return m.AttenuateBloomFilter
	}
	return nil
}

type PushFiltersRequest struct {
	AttenuateBloomFilter []byte   `protobuf:"bytes,1,opt,name=AttenuateBloomFilter,proto3" json:"AttenuateBloomFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushFiltersRequest) Reset()         { *m = PushFiltersRequest{} }
func (m *PushFiltersRequest) String() string { return proto.CompactTextString(m) }
func (*PushFiltersRequest) ProtoMessage()    {}
func (*PushFiltersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5a31b8d3937ded8, []int{2}
}
func (m *PushFiltersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFiltersRequest.Unmarshal(m, b)
}
func (m *PushFiltersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFiltersRequest.Marshal(b, m, deterministic)
}
func (dst *PushFiltersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFiltersRequest.Merge(dst, src)
}
func (m *PushFiltersRequest) XXX_Size() int {
	return xxx_messageInfo_PushFiltersRequest.Size(m)
}
func (m *PushFiltersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFiltersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushFiltersRequest proto.InternalMessageInfo

func (m *PushFiltersRequest) GetAttenuateBloomFilter() []byte {
	if m != nil {
		return m.AttenuateBloomFilter
	}
	return nil
}

type PushFiltersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushFiltersResponse) Reset()         { *m = PushFiltersResponse{} }
func (m *PushFiltersResponse) String() string { return proto.CompactTextString(m) }
func (*PushFiltersResponse) ProtoMessage()    {}
func (*PushFiltersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5a31b8d3937ded8, []int{3}
}
func (m *PushFiltersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFiltersResponse.Unmarshal(m, b)
}
func (m *PushFiltersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFiltersResponse.Marshal(b, m, deterministic)
}
func (dst *PushFiltersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFiltersResponse.Merge(dst, src)
}
func (m *PushFiltersResponse) XXX_Size() int {
	return xxx_messageInfo_PushFiltersResponse.Size(m)
}
func (m *PushFiltersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFiltersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushFiltersResponse proto.InternalMessageInfo

type Message struct {
	Type                 Message_MessageType  `protobuf:"varint,1,opt,name=type,enum=quasar.Message_MessageType" json:"type,omitempty"`
	RequestID            string               `protobuf:"bytes,2,opt,name=requestID" json:"requestID,omitempty"`
	PullFiltersRequest   *PullFiltersRequest  `protobuf:"bytes,3,opt,name=pullFiltersRequest" json:"pullFiltersRequest,omitempty"`
	PullFiltersResponse  *PullFiltersResponse `protobuf:"bytes,4,opt,name=pullFiltersResponse" json:"pullFiltersResponse,omitempty"`
	PushFilterRequest    *PushFiltersRequest  `protobuf:"bytes,5,opt,name=pushFilterRequest" json:"pushFilterRequest,omitempty"`
	PushFilterResponse   *PushFiltersResponse `protobuf:"bytes,6,opt,name=pushFilterResponse" json:"pushFilterResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_c5a31b8d3937ded8, []int{4}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_MessageType {
	if m != nil {
		return m.Type
	}
	return Message_PULL_FILTER_REQUEST
}

func (m *Message) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *Message) GetPullFiltersRequest() *PullFiltersRequest {
	if m != nil {
		return m.PullFiltersRequest
	}
	return nil
}

func (m *Message) GetPullFiltersResponse() *PullFiltersResponse {
	if m != nil {
		return m.PullFiltersResponse
	}
	return nil
}

func (m *Message) GetPushFilterRequest() *PushFiltersRequest {
	if m != nil {
		return m.PushFilterRequest
	}
	return nil
}

func (m *Message) GetPushFilterResponse() *PushFiltersResponse {
	if m != nil {
		return m.PushFilterResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*PullFiltersRequest)(nil), "quasar.PullFiltersRequest")
	proto.RegisterType((*PullFiltersResponse)(nil), "quasar.PullFiltersResponse")
	proto.RegisterType((*PushFiltersRequest)(nil), "quasar.PushFiltersRequest")
	proto.RegisterType((*PushFiltersResponse)(nil), "quasar.PushFiltersResponse")
	proto.RegisterType((*Message)(nil), "quasar.Message")
	proto.RegisterEnum("quasar.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("pb/messages.proto", fileDescriptor_messages_c5a31b8d3937ded8) }

var fileDescriptor_messages_c5a31b8d3937ded8 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x6f, 0xba, 0x40,
	0x10, 0xc5, 0xff, 0xa8, 0x7f, 0x1b, 0xc7, 0xa6, 0xd1, 0xd1, 0xa6, 0xa4, 0xf6, 0x60, 0x38, 0x79,
	0xc2, 0x84, 0x7e, 0x82, 0x36, 0xc5, 0x40, 0x8b, 0x2d, 0x5d, 0xf0, 0x6c, 0x30, 0xd9, 0xb4, 0x4d,
	0x50, 0x56, 0x76, 0x39, 0xf8, 0xe5, 0x9b, 0x06, 0x56, 0xaa, 0xb0, 0x9c, 0x7a, 0x22, 0x99, 0x37,
	0xef, 0xed, 0x9b, 0x5f, 0x80, 0x21, 0xdb, 0xcc, 0xb7, 0x94, 0xf3, 0xe8, 0x83, 0x72, 0x93, 0xa5,
	0x89, 0x48, 0xb0, 0xbb, 0xcf, 0x22, 0x1e, 0xa5, 0xc6, 0x18, 0xd0, 0xcf, 0xe2, 0x78, 0xf1, 0x15,
	0x0b, 0x9a, 0x72, 0x42, 0xf7, 0x19, 0xe5, 0xc2, 0x70, 0x61, 0x54, 0x99, 0x72, 0x96, 0xec, 0x38,
	0x45, 0x0b, 0xc6, 0x0f, 0x42, 0xd0, 0x5d, 0x16, 0x09, 0xfa, 0x18, 0x27, 0xc9, 0x56, 0x2e, 0xe8,
	0xda, 0x54, 0x9b, 0x5d, 0x92, 0x46, 0xcd, 0x70, 0xf2, 0x07, 0xf8, 0x67, 0xf5, 0x81, 0x3f, 0x25,
	0x5d, 0xe7, 0xa5, 0xce, 0x92, 0x64, 0x29, 0xe3, 0xbb, 0x0d, 0x17, 0x4b, 0x79, 0x1c, 0xce, 0xa1,
	0x23, 0x0e, 0x8c, 0x16, 0x31, 0x57, 0xd6, 0xc4, 0x94, 0x47, 0x9a, 0x47, 0xb9, 0xfc, 0x86, 0x07,
	0x46, 0x49, 0xb1, 0x88, 0x77, 0xd0, 0x4b, 0x65, 0x25, 0xf7, 0x49, 0x6f, 0x4d, 0xb5, 0x59, 0x8f,
	0x9c, 0x06, 0xf8, 0x0c, 0xc8, 0x14, 0x38, 0x7a, 0x7b, 0xaa, 0xcd, 0xfa, 0xd6, 0x6d, 0x19, 0xae,
	0xe2, 0x23, 0x0d, 0x2e, 0x5c, 0xc2, 0x88, 0xa9, 0x48, 0xf5, 0x4e, 0x11, 0x36, 0x69, 0x0c, 0x93,
	0x2b, 0xa4, 0xc9, 0x87, 0x0e, 0x0c, 0xd9, 0x2f, 0x8c, 0xb2, 0xd9, 0xff, 0x7a, 0xb3, 0x3a, 0x77,
	0xa2, 0x9a, 0xf0, 0x25, 0x3f, 0xf2, 0x34, 0x3c, 0xf6, 0xea, 0xd6, 0x7b, 0x29, 0xe0, 0x49, 0x83,
	0xcd, 0x48, 0xa1, 0x7f, 0x06, 0x19, 0x6f, 0x60, 0xe4, 0xaf, 0x3c, 0x6f, 0xbd, 0x70, 0xbd, 0xd0,
	0x26, 0x6b, 0x62, 0xbf, 0xaf, 0xec, 0x20, 0x1c, 0xfc, 0x43, 0x1d, 0xc6, 0x55, 0x21, 0xf0, 0xdf,
	0x5e, 0x03, 0x7b, 0xa0, 0x49, 0x4b, 0xe0, 0xd4, 0x2d, 0x2d, 0x55, 0xc8, 0x2d, 0xf6, 0xa0, 0xbd,
	0xe9, 0x16, 0x7f, 0xf4, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xef, 0x47, 0x6c, 0xe6,
	0x02, 0x00, 0x00,
}
