// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/messages.proto

package quasar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_PULL_FILTER_REQUEST  Message_MessageType = 0
	Message_PULL_FILTER_RESPONSE Message_MessageType = 1
)

var Message_MessageType_name = map[int32]string{
	0: "PULL_FILTER_REQUEST",
	1: "PULL_FILTER_RESPONSE",
}
var Message_MessageType_value = map[string]int32{
	"PULL_FILTER_REQUEST":  0,
	"PULL_FILTER_RESPONSE": 1,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_6096e0da1c3eda6b, []int{2, 0}
}

type PullFiltersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFiltersRequest) Reset()         { *m = PullFiltersRequest{} }
func (m *PullFiltersRequest) String() string { return proto.CompactTextString(m) }
func (*PullFiltersRequest) ProtoMessage()    {}
func (*PullFiltersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_6096e0da1c3eda6b, []int{0}
}
func (m *PullFiltersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFiltersRequest.Unmarshal(m, b)
}
func (m *PullFiltersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFiltersRequest.Marshal(b, m, deterministic)
}
func (dst *PullFiltersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFiltersRequest.Merge(dst, src)
}
func (m *PullFiltersRequest) XXX_Size() int {
	return xxx_messageInfo_PullFiltersRequest.Size(m)
}
func (m *PullFiltersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFiltersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullFiltersRequest proto.InternalMessageInfo

type PullFiltersResponse struct {
	BloomFilter          []byte   `protobuf:"bytes,1,opt,name=bloomFilter,proto3" json:"bloomFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFiltersResponse) Reset()         { *m = PullFiltersResponse{} }
func (m *PullFiltersResponse) String() string { return proto.CompactTextString(m) }
func (*PullFiltersResponse) ProtoMessage()    {}
func (*PullFiltersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_6096e0da1c3eda6b, []int{1}
}
func (m *PullFiltersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFiltersResponse.Unmarshal(m, b)
}
func (m *PullFiltersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFiltersResponse.Marshal(b, m, deterministic)
}
func (dst *PullFiltersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFiltersResponse.Merge(dst, src)
}
func (m *PullFiltersResponse) XXX_Size() int {
	return xxx_messageInfo_PullFiltersResponse.Size(m)
}
func (m *PullFiltersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFiltersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullFiltersResponse proto.InternalMessageInfo

func (m *PullFiltersResponse) GetBloomFilter() []byte {
	if m != nil {
		return m.BloomFilter
	}
	return nil
}

type Message struct {
	Type                 Message_MessageType  `protobuf:"varint,1,opt,name=type,enum=quasar.Message_MessageType" json:"type,omitempty"`
	RequestID            string               `protobuf:"bytes,2,opt,name=requestID" json:"requestID,omitempty"`
	PullFiltersRequest   *PullFiltersRequest  `protobuf:"bytes,3,opt,name=pullFiltersRequest" json:"pullFiltersRequest,omitempty"`
	PullFiltersResponse  *PullFiltersResponse `protobuf:"bytes,4,opt,name=pullFiltersResponse" json:"pullFiltersResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_6096e0da1c3eda6b, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_MessageType {
	if m != nil {
		return m.Type
	}
	return Message_PULL_FILTER_REQUEST
}

func (m *Message) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *Message) GetPullFiltersRequest() *PullFiltersRequest {
	if m != nil {
		return m.PullFiltersRequest
	}
	return nil
}

func (m *Message) GetPullFiltersResponse() *PullFiltersResponse {
	if m != nil {
		return m.PullFiltersResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*PullFiltersRequest)(nil), "quasar.PullFiltersRequest")
	proto.RegisterType((*PullFiltersResponse)(nil), "quasar.PullFiltersResponse")
	proto.RegisterType((*Message)(nil), "quasar.Message")
	proto.RegisterEnum("quasar.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("pb/messages.proto", fileDescriptor_messages_6096e0da1c3eda6b) }

var fileDescriptor_messages_6096e0da1c3eda6b = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0xd2, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b,
	0x2c, 0x4d, 0x2c, 0x4e, 0x2c, 0x52, 0x12, 0xe1, 0x12, 0x0a, 0x28, 0xcd, 0xc9, 0x71, 0xcb, 0xcc,
	0x29, 0x49, 0x2d, 0x2a, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe7, 0x12, 0x46,
	0x11, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x52, 0xe0, 0xe2, 0x4e, 0xca, 0xc9, 0xcf, 0xcf,
	0x85, 0x88, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x0b, 0x29, 0x6d, 0x65, 0xe2, 0x62,
	0xf7, 0x85, 0xd8, 0x24, 0xa4, 0xcf, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x0a, 0x56, 0xc6, 0x67, 0x24,
	0xad, 0x07, 0xb1, 0x51, 0x0f, 0x2a, 0x0d, 0xa3, 0x43, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0x0a, 0x85,
	0x64, 0xb8, 0x38, 0x8b, 0x20, 0x0e, 0xf0, 0x74, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x42,
	0x08, 0x08, 0x79, 0x71, 0x09, 0x15, 0x60, 0xb8, 0x54, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x48,
	0x0a, 0x66, 0x38, 0xa6, 0x5f, 0x82, 0xb0, 0xe8, 0x12, 0xf2, 0xe5, 0x12, 0x2e, 0xc0, 0xf4, 0x9f,
	0x04, 0x0b, 0xd8, 0x30, 0x69, 0xac, 0x86, 0x41, 0x94, 0x04, 0x61, 0xd3, 0xa7, 0xe4, 0xc0, 0xc5,
	0x8d, 0xe4, 0x1b, 0x21, 0x71, 0x2e, 0xe1, 0x80, 0x50, 0x1f, 0x9f, 0x78, 0x37, 0x4f, 0x9f, 0x10,
	0xd7, 0xa0, 0xf8, 0x20, 0xd7, 0xc0, 0x50, 0xd7, 0xe0, 0x10, 0x01, 0x06, 0x21, 0x09, 0x2e, 0x11,
	0x54, 0x89, 0xe0, 0x00, 0x7f, 0xbf, 0x60, 0x57, 0x01, 0xc6, 0x24, 0x36, 0x70, 0xac, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x55, 0xd6, 0xfd, 0xaa, 0x01, 0x00, 0x00,
}
